---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
  namespace: test-ns
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: javawebapp
  template:
    metadata: 
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: kkeducationb2/java-webapp:1.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080



# EX2 set based


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - javawebapp1
          - javawebapp2
          - javawebapp
  template:
    metadata:
      labels:
        app: javawebapp1  # or javawebapp2 or javawebapp, make sure this matches your selector
    spec:
      containers:
        - name: javawebapp
          image: kkeducationb2/java-webapp:1.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp1  # or javawebapp2 or javawebapp, make sure this matches your ReplicaSet's pods
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      






 
